agent {
    # Local working directory.
    data_dir = "/run/spire/data/agent"
    log_level = "DEBUG"
    # Points to the SPIRE Server for attestation and SVID fetching
    #  SPIRE Server hostname inside Docker for this PoC
    server_address = "spire-server"
    server_port = 8081
     # Unix Domain Socket exposed to workloads.
     # Applications never communicate directly with the SPIRE Server. 
     # They request identities from this socket.
    socket_path = "/run/spire/sockets/agent.sock"
    trust_domain = "poc.local"

    # DEVELOPMENT ONLY
    # Skips verification of the SPIRE Server's trust bundle during bootstrap.
    # Production environments should distribute the trust bundle securely instead.
    insecure_bootstrap = true
}

plugins {
    # Proves the agent's identity to the server using the join token
    NodeAttestor "join_token" {
        plugin_data {}
    }
    # Manages the agent's localized keys
    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data/agent"
        }
    }
    # Determines how the agent verifies workloads requesting identities.
    # Unix process selectors such as: 
    # - Executable path
    # - UID
    # - GID
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}