# The SPIFFE Helper uses this config to know how to fetch and format credentials

# Where to contact the SPIRE Agent's Workload API
# SPIFFE Helper continuously watches this socket for indentity updates
agent_address = "/run/spire/sockets/agent.sock"

cmd = ""
cmd_args = ""

# The target directory inside the container to drop the generated credentials.
# In docker-compose, this is mapped to the local './shared-credentials' folder.
cert_dir = "/var/run/credentials"

# X.509 mTLS output filenames
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "svid_bundle.pem"

# Configuration for generating an OIDC JSON Web Token (JWT).
jwt_svids = [
    {
        # The 'audience' must exactly match the WIF Provider audience configured in GCP
        jwt_audience = "gcp-wif"
        # The output file the Go application will read
        jwt_svid_file_name = "token.jwt"
    }
]