server {
    # Listen on all container interfaces.
    bind_address = "0.0.0.0"
    # SPIRE Server gRPC endpoint.
    bind_port = 8081
    # Defines the SPIFFE Trust Domain.
    # Every SPIFFE ID issued by this server belongs here.
    trust_domain = "poc.local"
    # Persistent storage location.
    data_dir = "/run/spire/data/server"
    # Verbose logging for learning/debugging.
    log_level = "DEBUG"
    # Crucial for GCP Workload Identity Federation (WIF). This must match the 
    # issuer expected by the OIDC configuration in Google Cloud.
    jwt_issuer = "https://poc.local"
}

plugins {
    # Stores the identity registration entries and agent attestations
    DataStore "sql" {
        # Stores:
        # - Registration Entries
        # - Node records
        # - Workload identities
        # - Trust bundles
        plugin_data {
             # SQLite is used only for this PoC.
            database_type = "sqlite3"
            connection_string = "/run/spire/data/server/datastore.sqlite3"
        }
    }
    # Allows new SPIRE Agents to join
    # using a one-time bootstrap token.
    NodeAttestor "join_token" {
        plugin_data {}
    }
    # Manages the server's signing keys. These keys are used to sign every JWT-SVID issued by the server. 
    # (stored locally for this PoC)
    KeyManager "disk" {
        plugin_data {
            keys_path = "/run/spire/data/server/keys.json"
        }
    }
}